# =================================================================
# End-to-End Pipeline Execution Script
# =================================================================
# This script runs all stages of the high-frequency return
# prediction pipeline in the correct logical order.
#
# It ensures that data is processed before being used for
# analysis, training, and backtesting.
#
# Use this script to generate all results for the report.
# From the project root directory, run:
# sh run.sh
# or
# bash run.sh
# =================================================================

# Exit immediately if any command fails, ensuring script integrity.
set -e

# --- STAGE 1: Data Loading & Preprocessing ---
echo "\n[PIPELINE] ==> STAGE 1: Loading and Preprocessing Raw Data..."
python main.py --load-data
echo "[PIPELINE] <== STAGE 1: Complete.\n"

# --- STAGE 2: Exploratory Data Analysis (EDA) ---
echo "\n[PIPELINE] ==> STAGE 2: Running Exploratory Data Analysis..."
python main.py --data-analysis
echo "[PIPELINE] <== STAGE 2: Complete.\n"

# --- STAGE 3: Benchmark Model Training ---
echo "\n[PIPELINE] ==> STAGE 3: Training All Benchmark Models (Linear & Time Series)..."
python main.py --train-benchmarks
echo "[PIPELINE] <== STAGE 3: Complete.\n"

# --- STAGE 4: Benchmark Model Evaluation ---
echo "\n[PIPELINE] ==> STAGE 4: Generating Reports for Benchmark Models..."
python main.py --evaluate-benchmarks
echo "[PIPELINE] <== STAGE 4: Complete.\n"

# --- STAGE 5: Transformer Model Training ---
echo "\n[PIPELINE] ==> STAGE 5: Training Transformer Model Experiments..."
python main.py --train-transformer
echo "[PIPELINE] <== STAGE 5: Complete.\n"

# --- STAGE 6: Strategy Backtesting ---
# This stage runs last as it depends on the prediction files
# generated by the training stages.
echo "\n[PIPELINE] ==> STAGE 6: Running Trading Strategy Backtest on All Models..."
python main.py --strategy
echo "[PIPELINE] <== STAGE 6: Complete.\n"

# --- End of Pipeline ---
echo "\n[PIPELINE] >>> Full end-to-end execution finished successfully. All results have been generated. <<<"